name: business_manager
description: "Business Manager."

publish_to: "none"

version: 2.0.1+1
# sdk: '>=3.4.3 <4.0.0'
environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  meta: ^1.10.0
  bloc_concurrency: ^0.2.2
  http: ^1.2.1
  equatable: ^2.0.5
  uuid: ^4.5.1
  connectivity_plus: ^6.1.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  permission_handler: ^11.1.0
  hive_flutter: ^1.1.0
  hive: ^2.0.0
  syncfusion_flutter_calendar: ^26.2.12
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.0
  flutter_widget_from_html_core: ^0.14.11
  url_launcher: ^6.0.0
  firebase_storage: ^12.3.3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.0
  pdf: ^3.11.1
  printing: ^5.13.2
  flutter_dotenv: ^5.1.0
  auto_route: ^9.2.2
  supabase_flutter: ^2.8.3
  fl_chart: ^0.69.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  cupertino_icons: ^1.0.2

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  auto_route_generator: ^9.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/images/star.png
    - assets/images/earth.png
    - assets/images/earth2.png
    - assets/images/earth3.png
    - assets/images/hom3.png
    - assets/images/home4.png
    - assets/images/space2.jpeg
    - assets/images/signin1.jpg
    - assets/images/signin2.png
    - assets/myfile.html
    - .env

  fonts:
    - family: Suse
      fonts:
        - asset: assets/fonts/suse/Suse-Light.ttf
          weight: 200
        - asset: assets/fonts/suse/Suse-Bold.ttf
          weight: 700

    - family: Jaro
      fonts:
        - asset: assets/fonts/jaro/Jaro-Regular.ttf
          weight: 200
        - asset: assets/fonts/jaro/Jaro_9pt-Regular.ttf
          weight: 700

    - family: Orbitron
      fonts:
        - asset: assets/fonts/orbitron/Orbitron-Regular.ttf
          weight: 200
        - asset: assets/fonts/orbitron/Orbitron-Bold.ttf
          weight: 700

    - family: Racing
      fonts:
        - asset: assets/fonts/racing/RacingSansOne-Regular.ttf
          weight: 200

    - family: Marker
      fonts:
        - asset: assets/fonts/marker/PermanentMarker-Regular.ttf
          weight: 200

    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/RubikWetPaint-Regular.ttf
          weight: 200
